language: python
dist: trusty
python:
  - "3.7"
  - "3.8"

addons:
  sonarcloud:
    organization: "project-alice-assistant"
    token:
      secure: $SONAR_TOKEN

script:
  - sudo apt-get update && sudo apt-get install libasound2-dev portaudio19-dev ffmpeg
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pytest tests/unittests/ --cov=core   --junitxml=result.xml
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
